[package]
name = "jour2tp"
version = "0.1.0"
edition = "2021"
default-run = "jour2tp"

[dependencies]
chrono = { version = "0.4", features = ["serde", "clock"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"